### ISSUE TITLE
Server panic on sigint

### ISSUE THREAD

**Issue by izaaklauer** [hashicorp/waypoint#1476]
**Describe the bug**
The waypoint server panic-crashed after sigint via ctrl-c, with the following trace:

```
2021-05-17T15:53:54.024Z [INFO]  waypoint.server.http: HTTP request: POST /hashicorp.waypoint.Waypoint/ListBuilds: date=2021-05-17T15:53:54.023985604Z http.host=34.201.38.155:9702 http.method=POST http.request_path=/hashicorp.waypoint.Waypoint/ListBuilds http.remote_addr=47.6.36.181 http.response_size=2504 http.scheme= http.status_code=200 http.useragent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36" http.version=HTTP/1.1
2021/05/17 15:53:54 http: TLS handshake error from 47.6.36.181:55081: remote error: tls: unknown certificate
2021-05-17T15:53:54.132Z [INFO]  waypoint.server.grpc: /hashicorp.waypoint.Waypoint/ListDeployments response: error=<nil> duration=169.069908ms
2021-05-17T15:53:54.132Z [INFO]  waypoint.server.http: HTTP request: POST /hashicorp.waypoint.Waypoint/ListDeployments: date=2021-05-17T15:53:53.962851867Z http.host=34.201.38.155:9702 http.method=POST http.request_path=/hashicorp.waypoint.Waypoint/ListDeployments http.remote_addr=47.6.36.181 http.response_size=1380 http.scheme= http.status_code=200 http.useragent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36" http.version=HTTP/1.1
^C2021-05-17T15:54:01.869Z [WARN]  waypoint: interrupt received, cancelling context
2021-05-17T15:54:01.870Z [INFO]  waypoint.server.grpc: /hashicorp.waypoint.Waypoint/GetLogStream response: error="context canceled" duration=3m6.962165008s
2021-05-17T15:54:01.870Z [INFO]  waypoint.server.http: HTTP request: POST /hashicorp.waypoint.Waypoint/GetLogStream: date=2021-05-17T15:50:54.907719383Z http.host=34.201.38.155:9702 http.method=POST http.request_path=/hashicorp.waypoint.Waypoint/GetLogStream http.remote_addr=47.6.36.181 http.response_size=0 http.scheme= http.status_code=200 http.useragent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36" http.version=HTTP/1.1
2021-05-17T15:54:01.870Z [INFO]  waypoint.server.grpc: shutting down gRPC server
panic: Drain() is not implemented

goroutine 613 [running]:
google.golang.org/grpc/internal/transport.(*serverHandlerTransport).Drain(0xc000f950e0)
	/home/circleci/go/pkg/mod/google.golang.org/grpc@v1.33.1/internal/transport/handler_server.go:440 +0x39
google.golang.org/grpc.(*Server).GracefulStop(0xc000818000)
	/home/circleci/go/pkg/mod/google.golang.org/grpc@v1.33.1/server.go:1683 +0x385
github.com/hashicorp/waypoint/internal/server.grpcInit.func2.1(0xc000e6cae0, 0x3317c78, 0xc0001383f0, 0xc000818000)
	/home/circleci/project/waypoint/internal/server/grpc.go:73 +0x91
created by github.com/hashicorp/waypoint/internal/server.grpcInit.func2
	/home/circleci/project/waypoint/internal/server/grpc.go:70 +0xa5
```

There was no ongoing build, deploy, or release at the time of the panic. 

**Steps to Reproduce**
Unfortunately, I haven't been able to reproduce this. I was running a server manually on ec2, with this command:

```
waypoint server run -accept-tos -advertise-addr=<addr> -listen-grpc=0.0.0.0:9701 -listen-http=0.0.0.0:9702 -db=/opt/waypoint/data.db -advertise-tls-skip-verify -vvv
```

**Expected behavior**
Graceful shutdown

**Waypoint Platform Versions**
Additional version and platform information to help triage the issue if
applicable:

* Waypoint CLI Version: v0.3.2
* Waypoint Server Platform and Version: v0.3.2

**Comment by izaaklauer** [comment]
It's a race condition.

### How to replicate: 

1. Change the GRPC Server's forceful stop timeout from 2 seconds to 15 seconds, and recompile the waypoint server: https://github.com/hashicorp/waypoint/blob/0e6d2e4302adc936ea70456241a6151e574a8e8e/internal/server/grpc.go#L92
2. Run the waypoint server.
3. Run `waypoint build` in some project
4. Visit the waypoint UI for that project, and click on the build stream, thereby initiating a websocket stream.
5. Ctrl-C the waypoint server

Sometimes this crashes right away with the panic above, and sometimes this panics after a few seconds, but it panics.

### Root cause

The GRPC server's [GracefulStop()](https://github.com/hashicorp/waypoint/blob/main/internal/server/grpc.go#L83) method doesn't know how to stop connections that have been initiated by ServeHTTP (see [here](https://github.com/grpc/grpc-go/issues/1384#issuecomment-317124531)).

Currently, if GracefulStop doesn't get to an http connection within 2 seconds, we call Stop() on server, which doesn't try to drain the http conns. This is what usually happens. If GracefulStop gets to them first, we panic.

### Potential solutions

The ideal solution is to close the http server process before we shut down the grpc server.

Currently, we have our GRPC and HTTP server processes in a run group:
https://github.com/hashicorp/waypoint/blob/0e6d2e4302adc936ea70456241a6151e574a8e8e/internal/server/server.go#L44-L60

When the run group cancels, it calls each agent's interrupt function in the order they were added. We need the GRPC server to be created first (because the HTTP server uses it), but we need the HTTP server to shut down first. There is an [old issue](https://github.com/oklog/run/issues/11) on oklog/run proposing reversing the agent interrupt order, which would fix this.

We could stop using a run group here to gain more control of shutdown order.
