### ISSUE TITLE
Bug: malformed GRPC bodies cause server panics

### ISSUE THREAD

**Issue by izaaklauer** [hashicorp/waypoint#1682]
**Describe the bug**

Waypoint crashes when exposed to malformed GRPC requests. This is a pretty general issue across multiple endpoints.

**Steps to Reproduce**

A few specific examples:

### Missing body panic

Failing to provide a request body causes server panics for `GetDeployment`, `GetRelease`, `GetBuild`, and potentially other endpoints.

`grpcurl --insecure -H "client-api-protocol: 1,1" -H "Authorization: <redacted>" localhost:9711 hashicorp.waypoint.Waypoint/GetDeployment`

Trace:

```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x2ce7a67]

goroutine 106 [running]:
github.com/hashicorp/waypoint/internal/server/singleprocess/state.(*appOperation).Get.func1(0xc000eb68c0, 0xc00061d600, 0xc000eb68c0)
	/home/circleci/project/waypoint/internal/server/singleprocess/state/app_operation.go:133 +0x47
github.com/boltdb/bolt.(*DB).View(0xc00000af00, 0xc00061d6e8, 0x0, 0x0)
	/home/circleci/go/pkg/mod/github.com/boltdb/bolt@v1.3.1/db.go:629 +0x93
github.com/hashicorp/waypoint/internal/server/singleprocess/state.(*appOperation).Get(0x722c1e0, 0xc000a90cc0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/circleci/project/waypoint/internal/server/singleprocess/state/app_operation.go:131 +0x12e
github.com/hashicorp/waypoint/internal/server/singleprocess/state.(*State).DeploymentGet(...)
	/home/circleci/project/waypoint/internal/server/singleprocess/state/deployment.go:25
github.com/hashicorp/waypoint/internal/server/singleprocess.(*service).GetDeployment(0xc00001b290, 0x3df9948, 0xc001173b30, 0xc000a0e780, 0xc00001b290, 0xc000ec46e0, 0xc001173830)
	/home/circleci/project/waypoint/internal/server/singleprocess/service_deploy.go:110 +0x4c
github.com/hashicorp/waypoint/internal/server/gen._Waypoint_GetDeployment_Handler.func1(0x3df9948, 0xc001173b30, 0x370c700, 0xc000a0e780, 0x65, 0x398930b, 0xd, 0x71f2680)
	/home/circleci/project/waypoint/internal/server/gen/server.pb.go:24757 +0x8b
github.com/hashicorp/waypoint/internal/server.authUnaryInterceptor.func1(0x3df9948, 0xc001173b30, 0x370c700, 0xc000a0e780, 0xc0013d6740, 0xc0008a0588, 0xc0008a0588, 0xc00061d8f0, 0x2c66805, 0x398930b)
	/home/circleci/project/waypoint/internal/server/auth.go:67 +0x266
google.golang.org/grpc.getChainUnaryHandler.func1(0x3df9948, 0xc001173b30, 0x370c700, 0xc000a0e780, 0x3df9948, 0xc001173b30, 0x0, 0x0)
	/home/circleci/go/pkg/mod/google.golang.org/grpc@v1.33.1/server.go:1051 +0xe7
github.com/hashicorp/waypoint/internal/server.versionUnaryInterceptor.func1(0x3df9948, 0xc001173ad0, 0x370c700, 0xc000a0e780, 0xc0013d6740, 0xc000a0e800, 0xc000a0e800, 0xc0011738f0, 0x34deac0, 0x73fb940)
	/home/circleci/project/waypoint/internal/server/grpc_version.go:35 +0xe2
google.golang.org/grpc.getChainUnaryHandler.func1(0x3df9948, 0xc001173ad0, 0x370c700, 0xc000a0e780, 0x0, 0x0, 0x0, 0x3df9948)
	/home/circleci/go/pkg/mod/google.golang.org/grpc@v1.33.1/server.go:1051 +0xe7
github.com/hashicorp/waypoint/internal/server.logUnaryInterceptor.func1(0x3df9948, 0xc0011738f0, 0x370c700, 0xc000a0e780, 0xc0013d6740, 0xc000a0e7c0, 0xc000a0e7c0, 0x18, 0x358a6c0, 0xc001173801)
	/home/circleci/project/waypoint/internal/server/grpc_log.go:36 +0x1b9
google.golang.org/grpc.chainUnaryServerInterceptors.func1(0x3df9948, 0xc0011738f0, 0x370c700, 0xc000a0e780, 0xc0013d6740, 0xc0008a0588, 0xc000c5cba0, 0x10d68c6, 0x3714340, 0xc0011738f0)
	/home/circleci/go/pkg/mod/google.golang.org/grpc@v1.33.1/server.go:1037 +0xd0
github.com/hashicorp/waypoint/internal/server/gen._Waypoint_GetDeployment_Handler(0x38fa740, 0xc00001b290, 0x3df9948, 0xc0011738f0, 0xc00069d740, 0xc00099bfa0, 0x3df9948, 0xc0011738f0, 0x0, 0x0)
	/home/circleci/project/waypoint/internal/server/gen/server.pb.go:24759 +0x150
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000f05a40, 0x3e1a8b8, 0xc00096c780, 0xc0011e7d00, 0xc000563140, 0x739fd10, 0x0, 0x0, 0x0)
	/home/circleci/go/pkg/mod/google.golang.org/grpc@v1.33.1/server.go:1210 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000f05a40, 0x3e1a8b8, 0xc00096c780, 0xc0011e7d00, 0x0)
	/home/circleci/go/pkg/mod/google.golang.org/grpc@v1.33.1/server.go:1533 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000e80620, 0xc000f05a40, 0x3e1a8b8, 0xc00096c780, 0xc0011e7d00)
	/home/circleci/go/pkg/mod/google.golang.org/grpc@v1.33.1/server.go:871 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/home/circleci/go/pkg/mod/google.golang.org/grpc@v1.33.1/server.go:869 +0x1fd
```

For the record, here's the GRPCurl response:
```
ERROR:
  Code: Unavailable
  Message: transport is closing
```

Nil checking inside our service implementations could fix this. For example, the following nil check [here in service_deploy.go](https://github.com/hashicorp/waypoint/blob/main/internal/server/singleprocess/service_deploy.go#L110)
```
	if req.Ref == nil {
		return nil, status.Errorf(codes.InvalidArgument, "missing required argument GetDeploymentRequest")
	}
```
Catches the issue. Similar fixes could be applied to other endpoints.

### Missing project ref causes server panic

Failing to include an application ref with a project in a GetDeployment request causes a panic.

Example:
`grpcurl -d '{"ref": {"sequence": { "number": 1 }}, "load_details": "0"}' --insecure -H "client-api-protocol: 1,1" -H "Authorization: <redacted>" localhost:9711 hashicorp.waypoint.Waypoint/GetDeployment`

Yields this panic:
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x2cc1d7a]

goroutine 40 [running]:
github.com/hashicorp/waypoint/internal/server/singleprocess/state.(*appOperation).getIdForSeq(0x722c1e0, 0xc0009583c0, 0xc000e84000, 0xc000a26aa0, 0xc000906680, 0x2c909cc, 0xc00000b0b0, 0xc00000af00, 0xc8)
	/home/circleci/project/waypoint/internal/server/singleprocess/state/app_operation.go:184 +0x7a
github.com/hashicorp/waypoint/internal/server/singleprocess/state.(*appOperation).Get.func1(0xc000e84000, 0xc000f8b600, 0xc000e84000)
	/home/circleci/project/waypoint/internal/server/singleprocess/state/app_operation.go:139 +0xc5
github.com/boltdb/bolt.(*DB).View(0xc00000af00, 0xc000f8b6e8, 0x0, 0x0)
	/home/circleci/go/pkg/mod/github.com/boltdb/bolt@v1.3.1/db.go:629 +0x93
github.com/hashicorp/waypoint/internal/server/singleprocess/state.(*appOperation).Get(0x722c1e0, 0xc0009583c0, 0xc000906640, 0x0, 0x0, 0x0, 0x0)
	/home/circleci/project/waypoint/internal/server/singleprocess/state/app_operation.go:131 +0x12e
github.com/hashicorp/waypoint/internal/server/singleprocess/state.(*State).DeploymentGet(...)
	/home/circleci/project/waypoint/internal/server/singleprocess/state/deployment.go:25
github.com/hashicorp/waypoint/internal/server/singleprocess.(*service).GetDeployment(0xc0004c2000, 0x3df9948, 0xc00082e960, 0xc0009065c0, 0xc0004c2000, 0xc000b754a0, 0xc00082e0f0)
	/home/circleci/project/waypoint/internal/server/singleprocess/service_deploy.go:110 +0x4c
github.com/hashicorp/waypoint/internal/server/gen._Waypoint_GetDeployment_Handler.func1(0x3df9948, 0xc00082e960, 0x370c700, 0xc0009065c0, 0x65, 0x398930b, 0xd, 0x71f2680)
	/home/circleci/project/waypoint/internal/server/gen/server.pb.go:24757 +0x8b
github.com/hashicorp/waypoint/internal/server.authUnaryInterceptor.func1(0x3df9948, 0xc00082e960, 0x370c700, 0xc0009065c0, 0xc000eac1a0, 0xc0004ba300, 0xc0004ba300, 0xc000f8b8f0, 0x2c66805, 0x398930b)
	/home/circleci/project/waypoint/internal/server/auth.go:67 +0x266
google.golang.org/grpc.getChainUnaryHandler.func1(0x3df9948, 0xc00082e960, 0x370c700, 0xc0009065c0, 0x3df9948, 0xc00082e960, 0x0, 0x0)
	/home/circleci/go/pkg/mod/google.golang.org/grpc@v1.33.1/server.go:1051 +0xe7
github.com/hashicorp/waypoint/internal/server.versionUnaryInterceptor.func1(0x3df9948, 0xc00082e900, 0x370c700, 0xc0009065c0, 0xc000eac1a0, 0xc000906700, 0xc000906700, 0xc00082e1e0, 0x34deac0, 0x73fb940)
	/home/circleci/project/waypoint/internal/server/grpc_version.go:35 +0xe2
google.golang.org/grpc.getChainUnaryHandler.func1(0x3df9948, 0xc00082e900, 0x370c700, 0xc0009065c0, 0x0, 0x0, 0x0, 0x3df9948)
	/home/circleci/go/pkg/mod/google.golang.org/grpc@v1.33.1/server.go:1051 +0xe7
github.com/hashicorp/waypoint/internal/server.logUnaryInterceptor.func1(0x3df9948, 0xc00082e1e0, 0x370c700, 0xc0009065c0, 0xc000eac1a0, 0xc0009066c0, 0xc0009066c0, 0x18, 0x358a6c0, 0xc00082e101)
	/home/circleci/project/waypoint/internal/server/grpc_log.go:36 +0x1b9
google.golang.org/grpc.chainUnaryServerInterceptors.func1(0x3df9948, 0xc00082e1e0, 0x370c700, 0xc0009065c0, 0xc000eac1a0, 0xc0004ba300, 0xc000eb5ba0, 0x10d68c6, 0x3714340, 0xc00082e1e0)
	/home/circleci/go/pkg/mod/google.golang.org/grpc@v1.33.1/server.go:1037 +0xd0
github.com/hashicorp/waypoint/internal/server/gen._Waypoint_GetDeployment_Handler(0x38fa740, 0xc0004c2000, 0x3df9948, 0xc00082e1e0, 0xc0007140c0, 0xc0007cfa00, 0x3df9948, 0xc00082e1e0, 0xc000ca4048, 0x6)
	/home/circleci/project/waypoint/internal/server/gen/server.pb.go:24759 +0x150
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000bcfc00, 0x3e1a8b8, 0xc00040fb00, 0xc000eaa000, 0xc000dfedb0, 0x739fd10, 0x0, 0x0, 0x0)
	/home/circleci/go/pkg/mod/google.golang.org/grpc@v1.33.1/server.go:1210 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000bcfc00, 0x3e1a8b8, 0xc00040fb00, 0xc000eaa000, 0x0)
	/home/circleci/go/pkg/mod/google.golang.org/grpc@v1.33.1/server.go:1533 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00098c6e0, 0xc000bcfc00, 0x3e1a8b8, 0xc00040fb00, 0xc000eaa000)
	/home/circleci/go/pkg/mod/google.golang.org/grpc@v1.33.1/server.go:871 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/home/circleci/go/pkg/mod/google.golang.org/grpc@v1.33.1/server.go:869 +0x1fd
```

For reference, a good request has the following body:
```json
{"ref": {"sequence": { "application": {"application": "example-nginx-2", "project": "example-nginx-2"}, "number": 1 }}, "load_details": "0"}
```

In this case, the nil check probably needs to happen after the protobuf has been type-cast, either [here](https://github.com/hashicorp/waypoint/blob/main/internal/server/singleprocess/state/app_operation.go#L138) or [here](https://github.com/hashicorp/waypoint/blob/main/internal/server/singleprocess/state/app_operation.go#L181).

**Expected behavior**

Return an InvalidArgument protobuf error and a helpful message.

**Waypoint Platform Versions**
Additional version and platform information to help triage the issue if
applicable:

* Waypoint CLI Version: 0.4.0
* Waypoint Server Platform and Version: 0.4.0
* Waypoint Plugin: n/a

**Additional context**

I'm filing this as a general issue because I suspect most endpoints are vulnerable.

**Comment by mitchellh** [comment]
We've added a general way to do request validation in 0.3 or 0.4, but we only added it to newer RPC endpoints. We should copy that style and add em to these endpoints.
