### ISSUE TITLE
Crash generated attempting to read current user

### ISSUE THREAD

**Issue by evanphx** [hashicorp/waypoint#1891]
Requests run by a runner appear to not have a user in the context, so using anything that attempts to read the user has to nil check atm, but it appears that GenerateLoginToken does not do that:

```
2021-07-20T02:47:59.483Z [INFO]  waypoint.server.singleprocess.poll_queuer.project: exiting
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x252453e]

goroutine 53 [running]:
github.com/hashicorp/waypoint/internal/server/singleprocess.(*service).GenerateLoginToken(0xc0005473b0, 0x330a780, 0xc000638040, 0xc00003dc60, 0x2, 0x2, 0x8)
        /tmp/wp-src/internal/server/singleprocess/auth.go:311 +0x9e
github.com/hashicorp/waypoint/internal/server/singleprocess.(*service).launchOndemandRunner(0xc0005473b0, 0x330a780, 0xc000638040, 0xc000f5c100, 0xc0001fee40, 0xc000f2aa00, 0xc00003ddb0, 0x40e0f8, 0x38, 0x2b8f0e0)
        /tmp/wp-src/internal/server/singleprocess/service_job.go:232 +0x256
github.com/hashicorp/waypoint/internal/server/singleprocess.(*service).QueueJob(0xc0005473b0, 0x330a780, 0xc000638040, 0xc000f2a640, 0xc0001fecc0, 0xc000f2a640, 0x0)
        /tmp/wp-src/internal/server/singleprocess/service_job.go:164 +0x488
github.com/hashicorp/waypoint/internal/server/singleprocess.(*service).runPollQueuer(0xc0005473b0, 0x330a780, 0xc000638040, 0xc000547428, 0x32f3448, 0xc0000a8010, 0x333d9b8, 0xc000598300)
        /tmp/wp-src/internal/server/singleprocess/poll.go:161 +0x557
created by github.com/hashicorp/waypoint/internal/server/singleprocess.New
        /tmp/wp-src/internal/server/singleprocess/service.go:163 +0x4c5
```

**Steps to Reproduce**
Call GenerateLoginToken from the context of QueueJob.

**Expected behavior**
The code would at least user a default user, or the QueueJob call should have included a token that had a user (it did have a token, so perhaps we're not setting that token up correctly to carry the default user?)

**Waypoint Platform Versions**
* main

**Comment by mitchellh** [comment]
This is fixed, this was an issue in Evan's branch.
