### ISSUE TITLE
Panic when attempting to get config from cli

### ISSUE THREAD

**Issue by marcotuna** [hashicorp/waypoint#2498]
**Describe the bug**
After an upgrade from version 0.5.2 to 0.6.0 (both server and cli), when attempting to get project configurations it returns no configuration at all (empty), however it should return configurations and when I specify the flag `-app` it throws a panic error.  

**Steps to Reproduce**
Steps to reproduce the behavior.

Configure a variable in waypoint (0.5.2 cli) with:

```
waypoint config set -app=test -workspace=test TEST_VAR=TEST_VALUE
```

Attempt to get that variable using waypoint cli 0.6.0  

```
waypoint config get -app=test

2021-10-15T08:45:49.921+0100 [INFO]  waypoint: waypoint version: full_string="v0.6.0 (e365aa8a)" version=v0.6.0 prerelease="" metadata="" revision=e365aa8a
2021-10-15T08:45:49.921+0100 [TRACE] waypoint: starting interrupt listener for context cancellation
2021-10-15T08:45:49.921+0100 [TRACE] waypoint: interrupt listener goroutine started
2021-10-15T08:45:49.921+0100 [DEBUG] waypoint: home configuration directory: path=/home/user/.config/waypoint
2021-10-15T08:45:49.922+0100 [TRACE] waypoint: no API client provided, initializing connection if possible
2021-10-15T08:45:49.922+0100 [INFO]  waypoint.server: attempting to source credentials and connect
2021-10-15T08:45:49.922+0100 [DEBUG] waypoint.serverclient: connection information: address=REDACTED tls=true tls_skip_verify=true send_auth=true has_token=true
2021-10-15T08:45:50.153+0100 [DEBUG] waypoint.server: connection established with sourced credentials
2021-10-15T08:45:50.153+0100 [TRACE] waypoint: requesting version info from server
2021-10-15T08:45:50.211+0100 [INFO]  waypoint: server version info: version=v0.6.0 api_min=1 api_current=1 entrypoint_min=1 entrypoint_current=1
2021-10-15T08:45:50.211+0100 [INFO]  waypoint: negotiated api version: version=1

2021-10-15T08:45:50.211+0100 [TRACE] waypoint: stopping signal listeners and cancelling the context
2021-10-15T08:45:50.212+0100 [WARN]  waypoint: context cancelled, stopping interrupt listener loop
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x2e5a172]

goroutine 1 [running]:
github.com/hashicorp/waypoint/internal/cli.(*ConfigGetCommand).Run(0xc0005ca228, 0xc000306b30, 0x1, 0x1, 0xc000a44570)
	/home/circleci/project/waypoint/internal/cli/config_get.go:80 +0x13b2
github.com/mitchellh/cli.(*CLI).Run(0xc00052e000, 0xc000d1fee8, 0x3e78958, 0xc0001ca500)
	/home/circleci/go/pkg/mod/github.com/mitchellh/cli@v1.1.2/cli.go:262 +0x41a
github.com/hashicorp/waypoint/internal/cli.Main(0xc000306b00, 0x4, 0x4, 0x0)
	/home/circleci/project/waypoint/internal/cli/main.go:126 +0x57a
main.main()
	/home/circleci/project/waypoint/cmd/waypoint/main.go:14 +0xa5
```

**Expected behavior**

**Waypoint Platform Versions**
Additional version and platform information to help triage the issue if
applicable:

* Waypoint CLI Version: 0.6.0
* Waypoint Server Platform and Version: `ecs`
* Waypoint Plugin: `aws/ecs`

**Additional context**
This problem is happening with the `cli`.
With `cli 0.5.2` with shows configuration and doesn't throw any error, despite the `-workspace` flag not working at all.
With `cli 0.6.0` it throws the panic error.

**Comment by catsby** [comment]
Thanks for opening this, and the suggested fix @marcotuna ! I'm going to investigate this a bit more before trying to apply that fix, just try and understand where we introduced the break and why
