### ISSUE TITLE
failed to determine if local vcs is dirty [...] against remote with url "\n" ref "HEAD"

### ISSUE THREAD

**Issue by azr** [hashicorp/waypoint#4066]
Hi there ! Looks like url was put in a kinda wrong state/place for that `Job_DataSource_Git`.

**Describe the bug**
I think it could have been after trying the `gitrefpretty()` function. A build started failing with :

```shellsession
❯ aws2-wrap --profile nv-automation-dev waypoint build         

» Building test...
! operation canceled
```

```shellsession
❯ WAYPOINT_LOG_LEVEL=trace aws2-wrap --profile nv-automation-dev waypoint build
2022-10-19T17:15:08.501+0200 [INFO]  waypoint: waypoint version: full_string="v0.10.2 (2c9926ef8)" version=v0.10.2 prerelease="" metadata="" revision=2c9926ef8
2022-10-19T17:15:08.501+0200 [TRACE] waypoint: starting interrupt listener for context cancellation
2022-10-19T17:15:08.501+0200 [TRACE] waypoint: interrupt listener goroutine started
2022-10-19T17:15:08.501+0200 [DEBUG] waypoint: home configuration directory: path=/Users/azr/Library/Preferences/waypoint
2022-10-19T17:15:08.503+0200 [TRACE] waypoint: no API client provided, initializing connection if possible
2022-10-19T17:15:08.503+0200 [TRACE] waypoint.server: Local server may be created later - server credentials optional
2022-10-19T17:15:08.503+0200 [INFO]  waypoint.server: attempting to source credentials and connect
2022-10-19T17:15:08.505+0200 [DEBUG] waypoint.serverclient: connection information: address=....elb.eu-west-1.amazonaws.com:9701 tls=true tls_skip_verify=true send_auth=true has_token=true
2022-10-19T17:15:08.903+0200 [DEBUG] waypoint.server: connection established with sourced credentials
2022-10-19T17:15:08.903+0200 [TRACE] waypoint: requesting version info from server
2022-10-19T17:15:08.956+0200 [INFO]  waypoint: server version info: version=v0.10.2 api_min=1 api_current=1 entrypoint_min=1 entrypoint_current=1
2022-10-19T17:15:08.956+0200 [INFO]  waypoint: negotiated api version: version=1
2022-10-19T17:15:08.956+0200 [DEBUG] waypoint: will operate on app: name=dobby
2022-10-19T17:15:08.956+0200 [DEBUG] waypoint.setupLocalJobSystem: determining if a local or remote runner should be used for this and future jobs

» Building dobby...2022-10-19T17:15:09.127+0200 [DEBUG] waypoint: Default runner profile exists - operation is possible remotely.
2022-10-19T17:15:09.127+0200 [DEBUG] waypoint.setupLocalJobSystem: Running this command: git -C /Users/azr/src/github.com/correct-path-to/test rev-parse --show-toplevel
2022-10-19T17:15:09.137+0200 [WARN]  waypoint.setupLocalJobSystem: failed to determine if local vcs is dirty:
  err=
  | failed to diff repo at "/Users/azr/src/github.com/correct-path-to/test" against remote with url "\n" ref "HEAD": Failed to get remote name for url 
  | : no remote with url matching "\n" found
  
2022-10-19T17:15:09.137+0200 [DEBUG] waypoint.setupLocalJobSystem: result: isLocal=false
2022-10-19T17:15:09.137+0200 [DEBUG] waypoint: queueing job: operation=*gen.Job_Build
2022-10-19T17:15:09.244+0200 [DEBUG] waypoint: opening job stream: job_id=01GFRD02BD6C8603HDF4DJB99D
2022-10-19T17:15:09.839+0200 [WARN]  waypoint: job failed: job_id=01GFRD02BD6C8603HDF4DJB99D code=Canceled message="Job dependency "01GFRD02BSYPKWMN979CQTY8C0" errored: ClientException: Container.image should not be null or empty."

! operation canceled
2022-10-19T17:15:09.839+0200 [TRACE] waypoint: stopping signal listeners and cancelling the context
```

**Steps to Reproduce**
* Do normal things with everything workging.
* Try to use the `gitrefpretty()` hcl func.

My file looks like this:

```hcl
app "dobby" {

  build {
    use "docker" {
      buildkit   = true
      dockerfile = "Dockerfile.test"
      build_args = {
        "GOPROXY" = var.GOPROXY
      }
    }

    registry {
      use "aws-ecr" {
        region     = var.aws_region
        repository = "test"
        // tag        = gitrefpretty(
        tag        = "latest"
      }
    }
  }
//...
}
```

**Waypoint Platform Versions**
Additional version and platform information to help triage the issue if
applicable:

* Waypoint CLI Version: v0.10.2 (2c9926ef8)
* Waypoint Server Platform and Version: ecs
* Waypoint Plugin: aws/ecs

**Comment by briancain** [comment]
Hey there @azr !! 👋🏻 

Do you think you could provide us with the output from running `waypoint project inspect <project-name>`? We're wondering if there might be a rogue new line `\n` in your git url:

```
2022-10-19T17:15:09.127+0200 [DEBUG] waypoint.setupLocalJobSystem: Running this command: git -C /Users/azr/src/github.com/correct-path-to/test rev-parse --show-toplevel
2022-10-19T17:15:09.137+0200 [WARN]  waypoint.setupLocalJobSystem: failed to determine if local vcs is dirty:
  err=
  | failed to diff repo at "/Users/azr/src/github.com/correct-path-to/test" against remote with url "\n" ref "HEAD": Failed to get remote name for url 
  | : no remote with url matching "\n" found
```

Also, we think this error is interesting:

```
2022-10-19T17:15:09.839+0200 [WARN]  waypoint: job failed: job_id=01GFRD02BD6C8603HDF4DJB99D code=Canceled message="Job dependency "01GFRD02BSYPKWMN979CQTY8C0" errored: ClientException: Container.image should not be null or empty."

! operation canceled
```

Although it could be an artifact of the git URL failure, so for now let's try to get that working first. Thanks!

**Comment by azr** [comment]
Hey Brian :D, sure thing:

```shellsession
❯ waypoint project inspect                 

» Project Info:
    Project Name: ...
    Applications: ...
      Workspaces: default
  Remote Enabled: true
     Data Source: Git
         Git URL: 

                   Git Ref: HEAD
  Data Source Poll Enabled: false
   App Status Poll Enabled: false
```

**Comment by briancain** [comment]
Interesting! Git URL seems be a blank and or new line. How did you go about setting your git data source? Was it via project apply, your `waypoint.hcl`, or maybe the UI? (also nice to see you again @azr 😄)

**Comment by azr** [comment]
Hem, I think I never set that value. I set up a waypoint with :

```shellsession
$ aws2-wrap --profile nv-automation-dev waypoint install -platform=ecs -ecs-cluster=automation-waypoint-server -accept-tos -ecs-region=eu-west-1 -plain
```

( before that I had a local desktop setup that I did destroy, the versions kept on bumping from the value it was at (`waypoint install --platform=docker -accept-tos`) )

Now that I think about it, I did go into the web ui at some point but never set that value, but kinda wondered why it was empty, and what value should be in there.

**Comment by azr** [comment]
That `Container.image should not be null or empty.` error prevents me from doing anything else or destroying everything to restart.

**Comment by azr** [comment]
Ah, sorry I'm spamming here: so I manually tore everything down and re-setup everything and things worked for two builds and then got the `remote "\n" url` thing again.

But that was after I got a panic because I used a `number` variable into a strin, ex:

```hcl
variable "aws_account_id" {
  type = string
}
[...]
    env = {
      FOO = "${var.aws_account_id}...."
    }
```

```
2022-10-20T12:21:12.788+0200 [DEBUG] waypoint.runner.app.dobby.mapper: plugin exited: job_id=01GFTEHVVQRQ44ZTPGN624V6NV job_op=*gen.Job_Up
panic: not a string

goroutine 101 [running]:
github.com/zclconf/go-cty/cty.Value.AsString({{{0x4698de8, 0xc00018cfc0}}, {0x3f49080, 0xc0006a7bf0}})
        /home/circleci/go/pkg/mod/github.com/zclconf/go-cty@v1.8.4/cty/value_ops.go:1256 +0x138
github.com/hashicorp/waypoint/internal/pkg/partial.renderTemplate(0xc000ef5b10, 0xc000bd5600)
        /home/circleci/project/waypoint/internal/pkg/partial/partial.go:75 +0xfd
github.com/hashicorp/waypoint/internal/pkg/partial.render(0x203000, {0x4697028, 0xc00017f3e0})
        /home/circleci/project/waypoint/internal/pkg/partial/partial.go:106 +0xed
github.com/hashicorp/waypoint/internal/pkg/partial.render(0x3b9dc00, {0x4696d88, 0xc000b70e00})
        /home/circleci/project/waypoint/internal/pkg/partial/partial.go:285 +0xb2d
github.com/hashicorp/waypoint/internal/pkg/partial.renderTop(0x1bc, {0x4696d88, 0xc000b70e00})
        /home/circleci/project/waypoint/internal/pkg/partial/partial.go:65 +0x54
github.com/hashicorp/waypoint/internal/pkg/partial.EvalExpression(0xc000ef5ad0, {0x4696d88, 0xc000b70e00})
        /home/circleci/project/waypoint/internal/pkg/partial/partial.go:52 +0x4f
github.com/hashicorp/waypoint/internal/config.configVars(0xc001472930, {0xc0000e6f00, 0x6, 0xc0017865e0}, 0xc0006a1660)
        /home/circleci/project/waypoint/internal/config/app_config.go:254 +0xa05
github.com/hashicorp/waypoint/internal/config.(*scopedConfig).configVars(0x0, 0x0, 0x3a01b40)
        /home/circleci/project/waypoint/internal/config/app_config.go:126 +0x134
github.com/hashicorp/waypoint/internal/config.(*genericConfig).configVars(0xc00130de60, 0x0)
        /home/circleci/project/waypoint/internal/config/app_config.go:157 +0xbf
github.com/hashicorp/waypoint/internal/config.(*genericConfig).ConfigVars(0xc00130de60)
        /home/circleci/project/waypoint/internal/config/app_config.go:144 +0x195
github.com/hashicorp/waypoint/internal/config.(*App).ConfigVars(0xc00055fd00)
        /home/circleci/project/waypoint/internal/config/app.go:147 +0x53
github.com/hashicorp/waypoint/internal/core.(*App).ConfigSync(0xc000c3b680, {0x46966c0, 0xc0005c2b00})
        /home/circleci/project/waypoint/internal/core/app_config.go:14 +0x73
github.com/hashicorp/waypoint/internal/core.(*deployOperation).Do(0xc000794150, {0x46966c0, 0xc0005c2b00}, {0x4725bf0, 0xc0013bae80}, 0x2, {0x4627ae0, 0xc0013ac900})
        /home/circleci/project/waypoint/internal/core/app_deploy.go:336 +0xcf
github.com/hashicorp/waypoint/internal/core.(*App).doOperation(0xc000c3b680, {0x46966c0, 0xc0005c2b00}, {0x4725bf0, 0xc0013ba200}, {0x46edca0, 0xc000794150})
        /home/circleci/project/waypoint/internal/core/operation.go:150 +0xa91
github.com/hashicorp/waypoint/internal/core.(*App).Deploy(0xc000c3b680, {0x46966c0, 0xc0005c2b00}, 0xc0001e3200)
        /home/circleci/project/waypoint/internal/core/app_deploy.go:48 +0x2f6
github.com/hashicorp/waypoint/internal/runner.(*Runner).executeDeployOp(0xc000cd0900, {0x46966c0, 0xc0005c2b00}, 0xc001787358, 0x2)
        /home/circleci/project/waypoint/internal/runner/operation_deploy.go:40 +0x172
github.com/hashicorp/waypoint/internal/runner.(*Runner).executeUpOp(0xc000cd0900, {0x46966c0, 0xc0005c2b00}, {0x4725bf0, 0xc00128b380}, 0xc0005eab00, 0xc000891580)
        /home/circleci/project/waypoint/internal/runner/operation_up.go:55 +0x42b
github.com/hashicorp/waypoint/internal/runner.(*Runner).executeJob(0xc000cd0900, {0x46966c0, 0xc0005c2b00}, {0x4725bf0, 0xc00128b380}, {0x46ede58, 0xc0012944e0}, 0xc0000d74a0, {0xc0000740c4, 0x33}, ...)
        /home/circleci/project/waypoint/internal/runner/operation.go:327 +0x269f
github.com/hashicorp/waypoint/internal/runner.(*Runner).prepareAndExecuteJob(0xc00056bef8, {0x46966c0, 0xc0005c2b00}, {0x4725bf0, 0xc00128b380}, {0x46ede58, 0xc0012944e0}, 0xc000e551b0, {0x46edeb0, 0xc000539a40}, ...)
        /home/circleci/project/waypoint/internal/runner/accept.go:611 +0x9a5
github.com/hashicorp/waypoint/internal/runner.(*Runner).accept(0xc000cd0900, {0x46966c0, 0xc0000e7a40}, {0x0, 0x0})
        /home/circleci/project/waypoint/internal/runner/accept.go:465 +0x1a70
github.com/hashicorp/waypoint/internal/runner.(*Runner).Accept(...)
        /home/circleci/project/waypoint/internal/runner/accept.go:110
github.com/hashicorp/waypoint/internal/runner.(*Runner).AcceptMany(0xc000cd0900, {0x46966c0, 0xc0000e7a40})
        /home/circleci/project/waypoint/internal/runner/accept.go:55 +0x45
github.com/hashicorp/waypoint/internal/client.(*Project).startRunner.func1()
        /home/circleci/project/waypoint/internal/client/runner.go:46 +0x73
created by github.com/hashicorp/waypoint/internal/client.(*Project).startRunner
        /home/circleci/project/waypoint/internal/client/runner.go:44 +0x23d
```

**Comment by briancain** [comment]
Thanks for the extra info here @azr -

Generally when you configure your Waypoint project, you can specify the git url via your `waypoint.hcl` like:


```hcl
runner {
  enabled = true

  data_source "git" {
    url  = "https://github.com/briancain/waypoint-tetris.git"
    path = ""
  }
}
```

Then when you go to `waypoint init` the project, the git url should be set up properly!

Now as far as the StartTask goes - this seems like a bug to me. Do you happen to have the full output logs for that job? And or maybe ECS has logs when it tried to start the task container?

Thank you!

**Comment by azr** [comment]
Hey @briancain, the full log output from the `waypoint up` command ?
I'll try to fetch that ECS log too, it's weird because now when I do the `up -local` way, it works now.

Also, there's that unknown missing task, which marks the deployment as not ready, and I'm not sure if I inadvertently created it:

![Screenshot 2022-10-25 at 16 56 46](https://user-images.githubusercontent.com/1024852/197808663-46ef97ad-5df3-4eb8-bdfc-1d972db55ee2.png)

**Comment by briancain** [comment]
> Hey @briancain, the full log output from the waypoint up command ?

It might be easier to find it via the static runner we setup. Since you installed on ECS, it should be running there alongside the Waypoint server! Those logs would show how it tried to launch those tasks. It might also be good to see what your runner profile looks like? You can find that via `waypoint runner profile list` and then `waypoint runner profile inspect <profile-id>`. These configurations are what Waypoint uses to launch remote tasks to run jobs.

> I'll try to fetch that ECS log too, it's weird because now when I do the up -local way, it works now.

Ah yes - well that makes sense! So a `StartTask` in waypoint is what we use to launch resources in your platform, so when you use a non-local run, it launches those tasks!

Very strange the ECS task launcher is having troubles launching resources 🤔
