### ISSUE TITLE
Panic when trying to use a number var in a string env

### ISSUE THREAD

**Issue by azr** [hashicorp/waypoint#4070]
Hello there ! On Waypoint v0.10.2

Using
```hcl
variable "aws_account_id" {
  type = number
} // set from the web ui on the server
[...]

app "test" {
    env = {
      FOO = "${var.aws_account_id}...."
    }
}
```

```
panic: not a string

goroutine 101 [running]:
github.com/zclconf/go-cty/cty.Value.AsString({{{0x4698de8, 0xc00018cfc0}}, {0x3f49080, 0xc0006a7bf0}})
        /home/circleci/go/pkg/mod/github.com/zclconf/go-cty@v1.8.4/cty/value_ops.go:1256 +0x138
github.com/hashicorp/waypoint/internal/pkg/partial.renderTemplate(0xc000ef5b10, 0xc000bd5600)
        /home/circleci/project/waypoint/internal/pkg/partial/partial.go:75 +0xfd
github.com/hashicorp/waypoint/internal/pkg/partial.render(0x203000, {0x4697028, 0xc00017f3e0})
        /home/circleci/project/waypoint/internal/pkg/partial/partial.go:106 +0xed
github.com/hashicorp/waypoint/internal/pkg/partial.render(0x3b9dc00, {0x4696d88, 0xc000b70e00})
        /home/circleci/project/waypoint/internal/pkg/partial/partial.go:285 +0xb2d
github.com/hashicorp/waypoint/internal/pkg/partial.renderTop(0x1bc, {0x4696d88, 0xc000b70e00})
        /home/circleci/project/waypoint/internal/pkg/partial/partial.go:65 +0x54
github.com/hashicorp/waypoint/internal/pkg/partial.EvalExpression(0xc000ef5ad0, {0x4696d88, 0xc000b70e00})
        /home/circleci/project/waypoint/internal/pkg/partial/partial.go:52 +0x4f
github.com/hashicorp/waypoint/internal/config.configVars(0xc001472930, {0xc0000e6f00, 0x6, 0xc0017865e0}, 0xc0006a1660)
        /home/circleci/project/waypoint/internal/config/app_config.go:254 +0xa05
github.com/hashicorp/waypoint/internal/config.(*scopedConfig).configVars(0x0, 0x0, 0x3a01b40)
        /home/circleci/project/waypoint/internal/config/app_config.go:126 +0x134
github.com/hashicorp/waypoint/internal/config.(*genericConfig).configVars(0xc00130de60, 0x0)
        /home/circleci/project/waypoint/internal/config/app_config.go:157 +0xbf
github.com/hashicorp/waypoint/internal/config.(*genericConfig).ConfigVars(0xc00130de60)
        /home/circleci/project/waypoint/internal/config/app_config.go:144 +0x195
github.com/hashicorp/waypoint/internal/config.(*App).ConfigVars(0xc00055fd00)
        /home/circleci/project/waypoint/internal/config/app.go:147 +0x53
github.com/hashicorp/waypoint/internal/core.(*App).ConfigSync(0xc000c3b680, {0x46966c0, 0xc0005c2b00})
        /home/circleci/project/waypoint/internal/core/app_config.go:14 +0x73
github.com/hashicorp/waypoint/internal/core.(*deployOperation).Do(0xc000794150, {0x46966c0, 0xc0005c2b00}, {0x4725bf0, 0xc0013bae80}, 0x2, {0x4627ae0, 0xc0013ac900})
        /home/circleci/project/waypoint/internal/core/app_deploy.go:336 +0xcf
github.com/hashicorp/waypoint/internal/core.(*App).doOperation(0xc000c3b680, {0x46966c0, 0xc0005c2b00}, {0x4725bf0, 0xc0013ba200}, {0x46edca0, 0xc000794150})
        /home/circleci/project/waypoint/internal/core/operation.go:150 +0xa91
github.com/hashicorp/waypoint/internal/core.(*App).Deploy(0xc000c3b680, {0x46966c0, 0xc0005c2b00}, 0xc0001e3200)
        /home/circleci/project/waypoint/internal/core/app_deploy.go:48 +0x2f6
github.com/hashicorp/waypoint/internal/runner.(*Runner).executeDeployOp(0xc000cd0900, {0x46966c0, 0xc0005c2b00}, 0xc001787358, 0x2)
        /home/circleci/project/waypoint/internal/runner/operation_deploy.go:40 +0x172
github.com/hashicorp/waypoint/internal/runner.(*Runner).executeUpOp(0xc000cd0900, {0x46966c0, 0xc0005c2b00}, {0x4725bf0, 0xc00128b380}, 0xc0005eab00, 0xc000891580)
        /home/circleci/project/waypoint/internal/runner/operation_up.go:55 +0x42b
github.com/hashicorp/waypoint/internal/runner.(*Runner).executeJob(0xc000cd0900, {0x46966c0, 0xc0005c2b00}, {0x4725bf0, 0xc00128b380}, {0x46ede58, 0xc0012944e0}, 0xc0000d74a0, {0xc0000740c4, 0x33}, ...)
        /home/circleci/project/waypoint/internal/runner/operation.go:327 +0x269f
github.com/hashicorp/waypoint/internal/runner.(*Runner).prepareAndExecuteJob(0xc00056bef8, {0x46966c0, 0xc0005c2b00}, {0x4725bf0, 0xc00128b380}, {0x46ede58, 0xc0012944e0}, 0xc000e551b0, {0x46edeb0, 0xc000539a40}, ...)
        /home/circleci/project/waypoint/internal/runner/accept.go:611 +0x9a5
github.com/hashicorp/waypoint/internal/runner.(*Runner).accept(0xc000cd0900, {0x46966c0, 0xc0000e7a40}, {0x0, 0x0})
        /home/circleci/project/waypoint/internal/runner/accept.go:465 +0x1a70
github.com/hashicorp/waypoint/internal/runner.(*Runner).Accept(...)
        /home/circleci/project/waypoint/internal/runner/accept.go:110
github.com/hashicorp/waypoint/internal/runner.(*Runner).AcceptMany(0xc000cd0900, {0x46966c0, 0xc0000e7a40})
        /home/circleci/project/waypoint/internal/runner/accept.go:55 +0x45
github.com/hashicorp/waypoint/internal/client.(*Project).startRunner.func1()
        /home/circleci/project/waypoint/internal/client/runner.go:46 +0x73
created by github.com/hashicorp/waypoint/internal/client.(*Project).startRunner
        /home/circleci/project/waypoint/internal/client/runner.go:44 +0x23d
```

**Comment by briancain** [comment]
Hey @azr - thanks for reporting this! We did have a recent fix come in for input vars of string type that panic, if you're building off `main` this might solve the issue?

https://github.com/hashicorp/waypoint/pull/4067

Otherwise we'll keep this open and get it fixed up! 🙏🏻
