### ISSUE TITLE
waypoint config crashes

### ISSUE THREAD

**Issue by vrischmann** [hashicorp/waypoint#473]
I installed waypoint via the Fedora repository.

The commande `waypoint config` crashes:
```
$ waypoint config
panic: flag redefined: app

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc0001584e0, 0x3ad3f60, 0xc000dac0e0, 0x341eea2, 0x3, 0x34900c8, 0x26)
        /usr/local/go/src/flag/flag.go:851 +0x4b8
github.com/hashicorp/waypoint/internal/pkg/flag.(*Set).Var(0xc000154700, 0x3ad3f60, 0xc000dac0e0, 0x341eea2, 0x3, 0x34900c8, 0x26)
        /home/circleci/project/waypoint/internal/pkg/flag/flag_var.go:79 +0x6f
github.com/hashicorp/waypoint/internal/pkg/flag.(*Set).VarFlag(0xc000154700, 0xc000bbaa00)
        /home/circleci/project/waypoint/internal/pkg/flag/flag_var.go:72 +0x1e1
github.com/hashicorp/waypoint/internal/pkg/flag.(*Set).StringVar(0xc000154700, 0xc000bba900)
        /home/circleci/project/waypoint/internal/pkg/flag/flag_string.go:33 +0x212
github.com/hashicorp/waypoint/internal/cli.(*ConfigGetCommand).Flags.func1(0xc000dce180)
        /home/circleci/project/waypoint/internal/cli/config_get.go:144 +0x18a
github.com/hashicorp/waypoint/internal/cli.(*baseCommand).flagSet(0xc00014a000, 0x0, 0xc000e9fb40, 0x41324b)
        /home/circleci/project/waypoint/internal/cli/base.go:415 +0x224
github.com/hashicorp/waypoint/internal/cli.(*ConfigGetCommand).Flags(0xc000d5dfc0, 0xc000e9fb98)
        /home/circleci/project/waypoint/internal/cli/config_get.go:130 +0x5a
github.com/hashicorp/waypoint/internal/cli.(*ConfigGetCommand).Help(0xc000d5dfc0, 0xc000dce150, 0x34314fa)
        /home/circleci/project/waypoint/internal/cli/config_get.go:171 +0x2f
github.com/mitchellh/cli.(*CLI).commandHelp(0xc00014a140, 0x3ab07c0, 0xc00000e020, 0x3b052e0, 0xc000d5d2e0)
        /go/pkg/mod/github.com/mitchellh/cli@v1.1.2/cli.go:575 +0x894
github.com/mitchellh/cli.(*CLI).Run(0xc00014a140, 0xc00014a140, 0xc000d5c000, 0xc000b822a0)
        /go/pkg/mod/github.com/mitchellh/cli@v1.1.2/cli.go:265 +0x227
github.com/hashicorp/waypoint/internal/cli.Main(0xc000cda9e0, 0x2, 0x2, 0x0)
        /home/circleci/project/waypoint/internal/cli/main.go:97 +0x4ee
main.main()
        /home/circleci/project/waypoint/cmd/waypoint/main.go:14 +0xa2
```

**Comment by mitchellh** [comment]
This snuck in unfortunately at the last minute. Easy fix, unfortunate. We'll get this fixed soon.

**Comment by gschier** [comment]
Looking forward to this fix as well! Glad to know it wasn't just me :)
