### ISSUE TITLE
Bug: panic in the config command

### ISSUE THREAD

**Issue by rugwirobaker** [hashicorp/waypoint#510]
**Describe the bug**
The whole config sub-command panics. And even `waypoint config` doesn't work

**Steps to Reproduce**
```sh
waypoint config set PORT='8080'
```
**Expected behavior**
I expect to set the specified environment variable to my current app

**Additional context**
Log ouput:

```sh
➜ ✗  waypoint config                
panic: flag redefined: app

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc000348120, 0x3ad3f60, 0xc0008a0520, 0x341eea2, 0x3, 0x34900c8, 0x26)
	/usr/local/go/src/flag/flag.go:851 +0x4b8
github.com/hashicorp/waypoint/internal/pkg/flag.(*Set).Var(0xc000352340, 0x3ad3f60, 0xc0008a0520, 0x341eea2, 0x3, 0x34900c8, 0x26)
	/home/circleci/project/waypoint/internal/pkg/flag/flag_var.go:79 +0x6f
github.com/hashicorp/waypoint/internal/pkg/flag.(*Set).VarFlag(0xc000352340, 0xc0005a0b80)
	/home/circleci/project/waypoint/internal/pkg/flag/flag_var.go:72 +0x1e1
github.com/hashicorp/waypoint/internal/pkg/flag.(*Set).StringVar(0xc000352340, 0xc0005a0a00)
	/home/circleci/project/waypoint/internal/pkg/flag/flag_string.go:33 +0x212
github.com/hashicorp/waypoint/internal/cli.(*ConfigGetCommand).Flags.func1(0xc000782600)
	/home/circleci/project/waypoint/internal/cli/config_get.go:144 +0x18a
github.com/hashicorp/waypoint/internal/cli.(*baseCommand).flagSet(0xc000ac4000, 0x0, 0xc00085db40, 0x41324b)
	/home/circleci/project/waypoint/internal/cli/base.go:415 +0x224
github.com/hashicorp/waypoint/internal/cli.(*ConfigGetCommand).Flags(0xc0008a0400, 0xc00085db98)
	/home/circleci/project/waypoint/internal/cli/config_get.go:130 +0x5a
github.com/hashicorp/waypoint/internal/cli.(*ConfigGetCommand).Help(0xc0008a0400, 0xc0007825d0, 0x34314fa)
	/home/circleci/project/waypoint/internal/cli/config_get.go:171 +0x2f
github.com/mitchellh/cli.(*CLI).commandHelp(0xc000ac4140, 0x3ab07c0, 0xc00000e020, 0x3b052e0, 0xc000385a00)
	/go/pkg/mod/github.com/mitchellh/cli@v1.1.2/cli.go:575 +0x894
github.com/mitchellh/cli.(*CLI).Run(0xc000ac4140, 0xc000ac4140, 0xc000384060, 0xc0007082a0)
	/go/pkg/mod/github.com/mitchellh/cli@v1.1.2/cli.go:265 +0x227
github.com/hashicorp/waypoint/internal/cli.Main(0xc00024f300, 0x2, 0x2, 0x0)
	/home/circleci/project/waypoint/internal/cli/main.go:97 +0x4ee
main.main()
	/home/circleci/project/waypoint/cmd/waypoint/main.go:14 +0xa2

```

**Comment by mitchellh** [comment]
This is fixed on main, we'll get a bug fix release out soon!

**Comment by rugwirobaker** [comment]
Thanks
