### ISSUE TITLE
panic when using Waypoint autocomplete

### ISSUE THREAD

**Issue by anubhavmishra** [hashicorp/waypoint#551]
**Describe the bug**
I installed the Waypoint shell autocomplete functionality using the `waypoint -autocomplete-install` command. When using autocomplete with a directory that doesn't have a `waypoint.hcl` file I see a panic.

```bash
waypoint panic: flag redefined: app

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc000326ae0, 0x46c7740, 0xc000b4b440, 0x40138cc, 0x3, 0x4084216, 0x26)
	/usr/local/go/src/flag/flag.go:851 +0x4b8
github.com/hashicorp/waypoint/internal/pkg/flag.(*Set).Var(0xc000445a00, 0x46c7740, 0xc000b4b440, 0x40138cc, 0x3, 0x4084216, 0x26)
	/home/circleci/project/waypoint/internal/pkg/flag/flag_var.go:79 +0x6f
github.com/hashicorp/waypoint/internal/pkg/flag.(*Set).VarFlag(0xc000445a00, 0xc000447d00)
	/home/circleci/project/waypoint/internal/pkg/flag/flag_var.go:72 +0x1e1
github.com/hashicorp/waypoint/internal/pkg/flag.(*Set).StringVar(0xc000445a00, 0xc000447c80)
	/home/circleci/project/waypoint/internal/pkg/flag/flag_string.go:33 +0x212
github.com/hashicorp/waypoint/internal/cli.(*ConfigGetCommand).Flags.func1(0xc000437260)
	/home/circleci/project/waypoint/internal/cli/config_get.go:144 +0x18a
github.com/hashicorp/waypoint/internal/cli.(*baseCommand).flagSet(0xc000438000, 0x0, 0xc000b9f4f0, 0x1)
	/home/circleci/project/waypoint/internal/cli/base.go:415 +0x224
github.com/hashicorp/waypoint/internal/cli.(*ConfigGetCommand).Flags(0xc000b4b360, 0xc431190)
	/home/circleci/project/waypoint/internal/cli/config_get.go:130 +0x5a
github.com/hashicorp/waypoint/internal/cli.(*ConfigGetCommand).AutocompleteFlags(0xc000b4b360, 0x0)
	/home/circleci/project/waypoint/internal/cli/config_get.go:157 +0x2b
github.com/mitchellh/cli.(*CLI).initAutocompleteSub.func1(0x4024013, 0xa, 0x3a20760, 0xc000a3a040, 0x0)
	/go/pkg/mod/github.com/mitchellh/cli@v1.1.2/cli.go:490 +0x2f8
github.com/armon/go-radix.recursiveWalk(0xc000436810, 0xc000b9f720, 0xc000b9f650)
	/go/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:519 +0xf0
github.com/armon/go-radix.recursiveWalk(0xc0004367e0, 0xc000b9f720, 0x1)
	/go/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:525 +0x7e
github.com/armon/go-radix.(*Tree).WalkPrefix(0xc000a3a280, 0xc00044a1d0, 0x7, 0xc000b9f720)
	/go/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:457 +0x142
github.com/mitchellh/cli.(*CLI).initAutocompleteSub(0xc000438140, 0x40188fc, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/mitchellh/cli@v1.1.2/cli.go:502 +0xdd
github.com/mitchellh/cli.(*CLI).initAutocompleteSub.func1(0x40188fc, 0x6, 0x3a20760, 0x414b290, 0xc000437140)
	/go/pkg/mod/github.com/mitchellh/cli@v1.1.2/cli.go:476 +0x189
github.com/armon/go-radix.recursiveWalk(0xc000436210, 0xc000b9f998, 0x3a20760)
	/go/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:519 +0xf0
github.com/armon/go-radix.recursiveWalk(0xc0004362a0, 0xc000b9f998, 0x0)
	/go/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:525 +0x7e
github.com/armon/go-radix.recursiveWalk(0xc000436090, 0xc000b9f998, 0xc00005426a)
	/go/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:525 +0x7e
github.com/armon/go-radix.(*Tree).WalkPrefix(0xc000a3a280, 0x0, 0x0, 0xc000b9f998)
	/go/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:457 +0x142
github.com/mitchellh/cli.(*CLI).initAutocompleteSub(0xc000438140, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/mitchellh/cli@v1.1.2/cli.go:502 +0xdd
github.com/mitchellh/cli.(*CLI).initAutocomplete(0xc000438140)
	/go/pkg/mod/github.com/mitchellh/cli@v1.1.2/cli.go:419 +0x202
github.com/mitchellh/cli.(*CLI).init(0xc000438140)
	/go/pkg/mod/github.com/mitchellh/cli@v1.1.2/cli.go:388 +0x389
sync.(*Once).doSlow(0xc000438208, 0xc000b9fe40)
	/usr/local/go/src/sync/once.go:66 +0xec
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:57
github.com/mitchellh/cli.(*CLI).Run(0xc000438140, 0xc000438140, 0xc00013e520, 0xc0008ffb20)
	/go/pkg/mod/github.com/mitchellh/cli@v1.1.2/cli.go:178 +0x8c2
github.com/hashicorp/waypoint/internal/cli.Main(0xc000910b40, 0x1, 0x1, 0x0)
	/home/circleci/project/waypoint/internal/cli/main.go:97 +0x4ee
main.main()
	/home/circleci/project/waypoint/cmd/waypoint/main.go:14 +0xa2
panic: flag redefined: app
```

**Steps to Reproduce**
Navigate to a directory that doesn't have a `waypoint.hcl` file and try to use the autocomplete by running the `waypoint` binary and using tab.

**Expected behavior**
Get a list of commands that are available for waypoint

**Additional context**
Waypoint v0.1.1 (44e2d3d6)

**Comment by mitchellh** [comment]
Fixed in main already :)
