### ISSUE TITLE
init panic from invalid waypoint.hcl

### ISSUE THREAD

**Issue by TylerReid** [hashicorp/waypoint#552]
I was following the tutorial and created this probably invalid config that passes validation:
```
project = "test"
app "test" {
    build {}
    deploy {}
}
```
From that a nil pointer panic happens
```
waypoint init
✓ Configuration file appears valid
✓ Connection to Waypoint server was successful
✓ Project "test" and all apps are registered with the server.
⠙ Validating required plugins...panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xdbe599]

goroutine 23 [running]:
github.com/hashicorp/waypoint/internal/config.trackPlugin(0x7230ba8, 0x0, 0x0, 0xc000efd8c0, 0x0, 0x1, 0x0, 0x0, 0x20)
        /home/circleci/project/waypoint/internal/config/plugin.go:46 +0x29
github.com/hashicorp/waypoint/internal/config.(*Config).Plugins(0xc000196c30, 0xc000ba2f60, 0x3ad3860, 0xc0009e3100)
        /home/circleci/project/waypoint/internal/config/plugin.go:21 +0x2d3
github.com/hashicorp/waypoint/internal/runner.(*Runner).executeJob(0xc000cd3440, 0x3b286a0, 0xc000188680, 0x3b6aca0, 0xc00073ed20, 0x3b4b8e0, 0xc0009e2ae0, 0xc00098a8f0, 0x0, 0x0, ...)
        /home/circleci/project/waypoint/internal/runner/operation.go:57 +0x239
github.com/hashicorp/waypoint/internal/runner.(*Runner).accept(0xc000cd3440, 0x3b286a0, 0xc000188680, 0xc00086c5e0, 0x1a, 0x0, 0x0)
        /home/circleci/project/waypoint/internal/runner/accept.go:213 +0x155f
github.com/hashicorp/waypoint/internal/runner.(*Runner).AcceptExact(...)
        /home/circleci/project/waypoint/internal/runner/accept.go:36
github.com/hashicorp/waypoint/internal/client.(*Project).doJob.func2.1(0xc00012eaa8, 0xc000cd3440, 0x3b286a0, 0xc00092c780, 0xc00086c5e0, 0x1a, 0x3b6aca0, 0xc0008c9c70)
        /home/circleci/project/waypoint/internal/client/job.go:91 +0x8e
created by github.com/hashicorp/waypoint/internal/client.(*Project).doJob.func2
        /home/circleci/project/waypoint/internal/client/job.go:89 +0x101
```

**Comment by mitchellh** [comment]
Good catch thank you. PR is up with a fix.
